// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Source: https://raw.githubusercontent.com/justdeleteme/justdelete.me/master/sites.json
// Refresh with: uv run scripts/fetch_justdeleteme.py
//
// Vendored snapshot of JustDeleteMe (https://justdelete.me/).
// Copyright (c) 2013 Robb Lewis & various contributors. MIT License.
// Full license text: extension/data/vendored/justdeleteme-LICENSE.md
//
// Filtered to entries graded `hard` or `impossible`. Consumed by
// `extension/src/rules/roach-motel-flag.ts` as a fallback after the
// hand-curated YAMLs under `extension/data/sites/*.yaml`.

export type JustDeleteMeDifficulty = "hard" | "impossible";

export interface JustDeleteMeEntry {
  name: string;
  // Canonical base hostnames (no `www.` prefix). The runtime
  // normalizes the location.hostname the same way before lookup.
  hostnames: readonly string[];
  difficulty: JustDeleteMeDifficulty;
  cancellationUrl: string | null;
  notes: string | null;
}

export const JUSTDELETEME_ENTRIES: readonly JustDeleteMeEntry[] = [
  {
    name: "Alibaba",
    hostnames: ["alibaba.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.alibaba.com/help/contact-us.html",
    notes: "Despite what it says in their FAQ there is actually no automatic way to delete your account. But they do see to be happy to do it if you ask them - you can contact them via http://www.alibaba.com/help/contact-us.html - I cancelled my account via their online chat system.",
  },
  {
    name: "Amazon",
    hostnames: ["amazon.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.amazon.com/gp/help/customer/contact-us/ref=cu_cf_email?ie=UTF8&mode=email#a",
    notes: "To close your account, contact Amazon by email (via this contact form) and request that your account be closed.",
  },
  {
    name: "Animal Crossing Community",
    hostnames: ["animalcrossingcommunity.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.animalcrossingcommunity.com/help_main.asp?HelpSectionID=5#Topic201",
    notes: "We do not 'delete' or 'terminate' accounts on ACC. If you no longer wish to use the site, you may delete all personal information from your profile and then stop logging in.",
  },
  {
    name: "Argyle Social",
    hostnames: ["app.argylesocial.com", "argylesocial.com"],
    difficulty: "impossible",
    cancellationUrl: "http://app.argylesocial.com/contact_us",
    notes: "Response from support@argylesocial.com: We really don't have a way to delete accounts entirely. The account won't be usable by anyone else, so there won't be any security issues. One smart thing to do to make doubly sure that everything is secure is to go to any social media pages that Argyle was authorized to use, and remove Argyle's authorization. Hope that helps",
  },
  {
    name: "iTunes / Apple ID",
    hostnames: ["apple.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.apple.com/support/itunes/contact/",
    notes: "Contact customer services. You will lose access to any media you haven\u2019t downloaded to your computer.",
  },
  {
    name: "Asos",
    hostnames: ["asos.de"],
    difficulty: "hard",
    cancellationUrl: "http://asos-de.custhelp.com/app/askchangedetails",
    notes: "Request deletion from customer services.",
  },
  {
    name: "Awdio.com",
    hostnames: ["awdio.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.awdio.com/pages/privacy-policy",
    notes: "Remove all songs from your account, then request deletion by emailing customer services.",
  },
  {
    name: "Backblaze",
    hostnames: ["backblaze.com"],
    difficulty: "impossible",
    cancellationUrl: "https://secure.backblaze.com/user_account.htm",
    notes: "Accounts cannot be deleted, even when contacting customer service. User account credentials will be permanently retained by Backblaze.",
  },
  {
    name: "Barnes and Noble",
    hostnames: ["barnesandnoble.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.barnesandnoble.com/customerservice/contactus",
    notes: "It is not possible to delete your Barnes and Noble account.  The best you can do is delete any personal information that you have stored on their website.",
  },
  {
    name: "Beam",
    hostnames: ["beam.pro"],
    difficulty: "hard",
    cancellationUrl: "https://beam.pro/legal/privacy",
    notes: "Remove all personal information from your account, then request deletion by emailing customer services.",
  },
  {
    name: "Blogger",
    hostnames: ["blogger.com"],
    difficulty: "impossible",
    cancellationUrl: "https://support.google.com/blogger/answer/41932",
    notes: "You can't delete your Blogger Account without deleting your entire Google Account. But you can delete your blog.",
  },
  {
    name: "Bodybuilding",
    hostnames: ["bodybuilding.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.bodybuilding.com/store/help/delete-bodyspace-account.htm",
    notes: "You can only deactivate your account by contacting support as they state on the help page. There is no way to permanently delete your account or data, and an inactive public profile will always be visible to public.",
  },
  {
    name: "BoerseBZ",
    hostnames: ["boerse.bz"],
    difficulty: "impossible",
    cancellationUrl: "http://www.boerse.bz/profile.php?do=delacc",
    notes: "Accounts cannot be removed at this time",
  },
  {
    name: "Bungie.net",
    hostnames: ["bungie.net"],
    difficulty: "impossible",
    cancellationUrl: "http://www.bungie.net/en-US/Forum/Post/66636671/0/0",
    notes: "TL;DR you can't do it. Discussion at http://www.bungie.net/en-US/Forum/Post/66636671/0/0",
  },
  {
    name: "BurstNET",
    hostnames: ["burst.net"],
    difficulty: "impossible",
    cancellationUrl: "http://burst.net/",
    notes: "Support staff refuses to delete accounts due to 'accounting purposes'",
  },
  {
    name: "Call of Duty (Activision)",
    hostnames: ["callofduty.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.callofduty.com/",
    notes: "'There is no way to close or shut down an account.'",
  },
  {
    name: "cex.io",
    hostnames: ["cex.io"],
    difficulty: "hard",
    cancellationUrl: "https://support.cex.io/hc/en-us/articles/201516097-How-can-I-delete-my-account-from-CEX-IO-and-GHash-IO-",
    notes: "You can't delete your account without contacting them. You must set the subject to 'Delete Account'",
  },
  {
    name: "Cinemagram",
    hostnames: ["cinemagr.am"],
    difficulty: "impossible",
    cancellationUrl: "",
    notes: "According to the app you can email feedback@cinemagr.am for questions. Unfortunatly removal requests aren't replied to.",
  },
  {
    name: "CiteULike",
    hostnames: ["citeulike.org"],
    difficulty: "impossible",
    cancellationUrl: "http://wiki.citeulike.org/index.php/Accounts#How_do_I_delete_my_account.3F",
    notes: "We don't delete old accounts.",
  },
  {
    name: "CleverReach",
    hostnames: ["cleverreach.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.cleverreach.com",
    notes: "Email customer services to request deletion",
  },
  {
    name: "Code Red",
    hostnames: ["cne.coderedweb.com", "coderedweb.com"],
    difficulty: "impossible",
    cancellationUrl: "https://cne.coderedweb.com",
    notes: "You can't delete yourself. You can only change your phone nr. to a bogus number.",
  },
  {
    name: "CNET Download",
    hostnames: ["cnet.com", "download.cnet.com"],
    difficulty: "hard",
    cancellationUrl: "https://cbsi.secure.force.com/CBSi/submitcase?template=template_cnet&referer=cnet.com&cfs=SFS_1",
    notes: "You have to ask the support to get your account deleted. Choose the category CNET Registration",
  },
  {
    name: "AppFog",
    hostnames: ["console.appfog.com", "appfog.com"],
    difficulty: "hard",
    cancellationUrl: "https://groups.google.com/forum/#!topic/appfog-users/H9AkHjHFfZk",
    notes: "Remove all applications and services from your account, then request deletion by emailing customer services.",
  },
  {
    name: "Couchsurfing",
    hostnames: ["couchsurfing.org"],
    difficulty: "impossible",
    cancellationUrl: "https://www.couchsurfing.org/delete_profile.html?delete=1",
    notes: "Cannot be deleted fully, reactivation is always available. Fill out the form and select 'I understand. Please delete my profile.'.",
  },
  {
    name: "Coursera",
    hostnames: ["coursera.org"],
    difficulty: "hard",
    cancellationUrl: "https://www.coursera.org/about/contact",
    notes: "Contact support and request they delete your account.",
  },
  {
    name: "Craigslist",
    hostnames: ["craigslist.org"],
    difficulty: "hard",
    cancellationUrl: "http://www.craigslist.org/about/help/user_accounts",
    notes: "Send an email to abuse@craigslist.org and request deletion.",
  },
  {
    name: "CreditExpert",
    hostnames: ["creditexpert.co.uk"],
    difficulty: "hard",
    cancellationUrl: "https://www.creditexpert.co.uk/",
    notes: "You can cancel by email but only if your membership includes insurance. Otherwise, an email cancellation will be ignored. You have to call 0800 561 0083 to cancel your account. This is the only way. More info here: http://experian.metafaq.com/help/CreditExpertBRS/Cancel_and_duration/CancelBRS",
  },
  {
    name: "Crushee",
    hostnames: ["crushee.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.crushee.com/pages/faq",
    notes: "They mock the very idea of wanting to delete your account in their faq: \"Can I delete my account cause I totally h8 you guise??!!!111\"",
  },
  {
    name: "Starbucks",
    hostnames: ["customerservice.starbucks.com", "starbucks.com"],
    difficulty: "impossible",
    cancellationUrl: "http://customerservice.starbucks.com/app/contact/ask_starbucks_website/",
    notes: "They will not delete your account but upon request they can \u201cscramble all of your information so that you don\u2019t receive emails and none of your information is available to [them] for potential fraud\u201d.",
  },
  {
    name: "Personello Germany",
    hostnames: ["de.personello.com"],
    difficulty: "hard",
    cancellationUrl: "http://de.personello.com/mypersonello/index/feedback",
    notes: "It is necessary to contact the support, for example through 'Mein Konto' -> 'Meinung abgeben'.",
  },
  {
    name: "OpenShift",
    hostnames: ["developers.openshift.com"],
    difficulty: "impossible",
    cancellationUrl: "https://developers.openshift.com/en/account-overview.html#_how_do_i_delete_my_account",
    notes: "You can't delete your account including all data, only a \u2018soft delete\u2019 is possible where you can always re-enable your account.",
  },
  {
    name: "Digg",
    hostnames: ["digg.com"],
    difficulty: "hard",
    cancellationUrl: "http://digg.com/contact",
    notes: "Contact Digg\u2019s customer support and request for your account to be closed.",
  },
  {
    name: "Discord",
    hostnames: ["discordapp.com"],
    difficulty: "hard",
    cancellationUrl: null,
    notes: "Contact Discord\u2019s customer support and request for your account to be closed.",
  },
  {
    name: "JSFiddle",
    hostnames: ["doc.jsfiddle.net", "jsfiddle.net"],
    difficulty: "hard",
    cancellationUrl: "http://doc.jsfiddle.net/meta/channels.html?highlight=contact",
    notes: "Please email a request if you\u2019d like your account to be deleted.",
  },
  {
    name: "Dwell",
    hostnames: ["dwell.co.uk"],
    difficulty: "impossible",
    cancellationUrl: "https://dwell.co.uk/contactus.php",
    notes: "It\u2019s not possible to delete an account, you can either remove or replace your contact information with bogus details.",
  },
  {
    name: "eDreams",
    hostnames: ["edreams.co.uk", "edreams.net", "edreams.pt"],
    difficulty: "impossible",
    cancellationUrl: "http://www.edreams.com/edreams/english/about/copyright.jhtml",
    notes: "FAQ states that account can be deleted upon request, but e-mails requesting it are completely ignored.",
  },
  {
    name: "EdX",
    hostnames: ["edx.org"],
    difficulty: "impossible",
    cancellationUrl: "https://www.edx.org/student-faq",
    notes: "There's no need to delete your account. An old, unused edX account with no course completions associated with it will disappear.",
  },
  {
    name: "Elevate",
    hostnames: ["elevateapp.com"],
    difficulty: "hard",
    cancellationUrl: "http://elevateapp.com/",
    notes: "You must send an e-mail to hello@elevateapp.com requesting deletion. You will then receive a response from support asking for feedback and to confirm the deletion. The next e-mail you receive from support will notify you that your account has been deleted.",
  },
  {
    name: "WordPress.com",
    hostnames: ["en.support.wordpress.com", "wordpress.com"],
    difficulty: "impossible",
    cancellationUrl: "http://en.support.wordpress.com/deleting-accounts/",
    notes: "\u201cWordPress.com accounts cannot be deleted.\u201d The best you can do is remove any identifying data from your account.",
  },
  {
    name: "Wikipedia",
    hostnames: ["en.wikipedia.org", "wikipedia.org"],
    difficulty: "impossible",
    cancellationUrl: "https://en.wikipedia.org/wiki/Wikipedia:FAQ#How_do_I_change_my_username.2Fdelete_my_account.3F",
    notes: "'A username cannot be deleted.' However, they do have some suggestions.",
  },
  {
    name: "Envato",
    hostnames: ["envato.com", "themeforest.net", "codecanyon.net", "videohive.net", "audiojungle.net", "graphicriver.net", "photodune.net", "3docean.net", "activeden.net"],
    difficulty: "hard",
    cancellationUrl: "https://help.market.envato.com/hc/en-us/articles/202500394-How-Do-I-Close-My-Account-",
    notes: "You have to send them a request to delete the account using the contact form.",
  },
  {
    name: "eRepublik",
    hostnames: ["erepublik.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.erepublik.com/en/contact/none/none",
    notes: "Create new Game Support ticket to request account removal.",
  },
  {
    name: "Etsy",
    hostnames: ["etsy.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.etsy.com/help/article/53",
    notes: "You have to contact Etsy. As they've stated, \u201cwhen a member closes an account, it becomes inaccessible and will remain deactivated, unless the member requests it reopened. Account information remains securely on file with them, and Etsy has a detailed Privacy Policy that explains how we use members' information. This policy includes a statement regarding data retention.\u201d",
  },
  {
    name: "Battle.net",
    hostnames: ["eu.battle.net", "battle.net"],
    difficulty: "hard",
    cancellationUrl: "https://eu.battle.net/support/en/ticket/submit",
    notes: "Customer Support will require you to send a signed written letter confirming your wishes, your account details and a copy of legal identification (passport, drivers license) to your account region's office headquarters.",
  },
  {
    name: "Eventful",
    hostnames: ["eventful.com"],
    difficulty: "hard",
    cancellationUrl: "http://support.eventful.com/entries/25351895-How-do-I-cancel-delete-my-account-",
    notes: "Contact support and they will delete your account",
  },
  {
    name: "Evernote",
    hostnames: ["evernote.com"],
    difficulty: "impossible",
    cancellationUrl: "https://www.evernote.com/Deactivate.action",
    notes: "You cannot delete your Evernote account, just deactivate it temporarily. Deactivation does not remove your data so you will have to manually delete all notes and personal info, perform a sync and then deactivate the account.",
  },
  {
    name: "Experian",
    hostnames: ["experiandirect.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.experiandirect.com/triplealert/Message.aspx?PageTypeID=FAQ&WT.svl=faq&SiteVersionID=473&SiteID=100173&sc=657900&bcd=",
    notes: "You have to call or email them. They respond to email quickly, however, so it is not that painful.",
  },
  {
    name: "Startnext",
    hostnames: ["faq.startnext.de", "startnext.de"],
    difficulty: "hard",
    cancellationUrl: "http://faq.startnext.de/Nutzerprofil/id/Wie+kann+ich+mein+Startnext-Profil+loeschen+-26/modul/Nutzerprofil+%26+Registrierung/aid/18",
    notes: "You have to write an Email to the Support. Your activites will be anonymized.",
  },
  {
    name: "Fitbit",
    hostnames: ["fitbit.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.fitbit.com/",
    notes: "To delete or deactivate your account, contact Fitbit by email via the contact form.",
  },
  {
    name: "Flixster",
    hostnames: ["flixster.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.flixster.com/docs/privacy/",
    notes: "Email privacy@flixster-inc.com and ask to have your account deleted.",
  },
  {
    name: "Rotten Tomatoes",
    hostnames: ["flixster.desk.com", "desk.com"],
    difficulty: "hard",
    cancellationUrl: "http://flixster.desk.com/customer/portal/articles/169347-how-do-i-cancel-my-account-",
    notes: "You need to contact flixster to cancel a native RT profile, while Facebook linked or Flixster.com accounts are easier to cancel.",
  },
  {
    name: "Udacity",
    hostnames: ["forums.udacity.com", "udacity.com"],
    difficulty: "impossible",
    cancellationUrl: "http://forums.udacity.com/answer_link/100044663/",
    notes: "A Udacity employee recommends that you stop using the account, which means there's currently no way of deleting the account.",
  },
  {
    name: "Gamespot",
    hostnames: ["gamespot.custhelp.com", "custhelp.com"],
    difficulty: "hard",
    cancellationUrl: "https://gamespot.custhelp.com/app/ask",
    notes: "Account deletion requires contacting Customer Support.",
  },
  {
    name: "Gauges",
    hostnames: ["get.gaug.es", "gaug.es"],
    difficulty: "hard",
    cancellationUrl: "http://get.gaug.es/tos/",
    notes: "Contact support and request they delete your account.",
  },
  {
    name: "GFace",
    hostnames: ["gface.com", "crytek.kayako.com"],
    difficulty: "hard",
    cancellationUrl: "https://crytek.kayako.com/Tickets/Submit",
    notes: "You can't delete your account without contacting them. You must submit a ticket and set the subject to 'Delete Account'",
  },
  {
    name: "ghash.io",
    hostnames: ["ghash.io"],
    difficulty: "hard",
    cancellationUrl: "https://support.cex.io/hc/en-us/articles/201516097-How-can-I-delete-my-account-from-CEX-IO-and-GHash-IO-",
    notes: "You can't delete your account without contacting them. You must set the subject to 'Delete Account'",
  },
  {
    name: "GhostMail",
    hostnames: ["ghostmail.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.ghostmail.com/help",
    notes: "Send them an email with Delete my account as title.",
  },
  {
    name: "Giant Bomb",
    hostnames: ["giantbomb.com"],
    difficulty: "impossible",
    cancellationUrl: "https://auth.giantbomb.com/account/",
    notes: "You can't delete your account without contacting support.",
  },
  {
    name: "Glassboard",
    hostnames: ["glassboard.com"],
    difficulty: "hard",
    cancellationUrl: "http://glassboard.com/support/",
    notes: "Use the support email address to ask them to close your account.",
  },
  {
    name: "Glassdoor",
    hostnames: ["glassdoor.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.glassdoor.com/about/contact_input.htm?opt=cc",
    notes: "Contact customer services and request deletion.",
  },
  {
    name: "GMX",
    hostnames: ["gmx.net"],
    difficulty: "impossible",
    cancellationUrl: "http://www.gmx.net/",
    notes: "You can't delete your account, but you can deactivate it. (Start \u2192  Mein Account \u2192  Account stilllegen)",
  },
  {
    name: "Gogo",
    hostnames: ["gogoair.com"],
    difficulty: "hard",
    cancellationUrl: "http://custhelp.gogoinflight.com/",
    notes: "Email customercare@gogoair.com and ask to have your account deleted.",
  },
  {
    name: "Grailed",
    hostnames: ["grailed.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.grailed.com/",
    notes: "Send an email to arun@grailed.com and request deletion.",
  },
  {
    name: "Gravatar",
    hostnames: ["gravatar.com"],
    difficulty: "impossible",
    cancellationUrl: "http://gravatar.com",
    notes: "You can't delete your Gravatar Account without deleting your entire WordPress Account.",
  },
  {
    name: "Groupon",
    hostnames: ["groupon.com"],
    difficulty: "hard",
    cancellationUrl: "https://groupon.com/customer_support",
    notes: "According to Groupon's privacy statement, you have to contact support directly and ask them to delete your account.",
  },
  {
    name: "GrubHub",
    hostnames: ["grubhub.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.grubhub.com/legal/",
    notes: "Privacy Policy Letter D: Account e-mail addresses cannot be deleted. However, an Account may be closed and GrubHub will cause the corresponding e-mail address to be scrambled.",
  },
  {
    name: "Hackpad",
    hostnames: ["hackpad.com"],
    difficulty: "hard",
    cancellationUrl: "https://hackpad.com/Hackpad-FAQ-tq56fI63mz3#:h=Account-settings",
    notes: "We can do that for you - just send an email.",
  },
  {
    name: "Hack This Site",
    hostnames: ["hackthissite.org"],
    difficulty: "impossible",
    cancellationUrl: "https://www.hackthissite.org/forums/viewtopic.php?f=9&t=4800&sid=7edb515c2462108e30ddec760c2ddfebv",
    notes: "It is not possible to delete your Hack This Site account.  The best you can do is delete any personal information that you have stored on their website.",
  },
  {
    name: "Dwolla",
    hostnames: ["help.dwolla.com", "dwolla.com"],
    difficulty: "hard",
    cancellationUrl: "http://help.dwolla.com/customer/portal/articles/269223-how-can-i-delete-my-dwolla-account-",
    notes: "All accounts stay in their system for at least 3 years. Remove any banking information before you delete.",
  },
  {
    name: "EA Origin",
    hostnames: ["help.ea.com", "ea.com"],
    difficulty: "hard",
    cancellationUrl: "https://help.ea.com/en/contact-us/ask",
    notes: "Contact customer services to request deletion. If you're outside the US this must be by phone.",
  },
  {
    name: "Overstock",
    hostnames: ["help.overstock.com", "overstock.com"],
    difficulty: "hard",
    cancellationUrl: "https://help.overstock.com/app/contact_page",
    notes: "You must contact support directly and ask them to invalidate your account.  However, your transaction data may not be deleted from their records.",
  },
  {
    name: "Pandora",
    hostnames: ["help.pandora.com", "pandora.com"],
    difficulty: "hard",
    cancellationUrl: "http://help.pandora.com/customer/portal/articles/24624-cancel-account",
    notes: "You have to email support from the email associated with your account. If you do not have access to that, you need to provide the email address, birth year, and zip code on the account.",
  },
  {
    name: "Hi-Rez Studios",
    hostnames: ["hirezstudios.com"],
    difficulty: "impossible",
    cancellationUrl: "https://hi-rez.custhelp.com/app/answers/detail/a_id/249/~/removing-your-account",
    notes: null,
  },
  {
    name: "hitbox",
    hostnames: ["hitbox.tv"],
    difficulty: "hard",
    cancellationUrl: "http://help.hitbox.tv/customer/portal/emails/new",
    notes: "You have to send an email to the support team asking for deletion of your account. Your account will be added to a list of accounts for deletion, and it may take some time before it has actually been deleted.",
  },
  {
    name: "HOL Virtual Hogwarts",
    hostnames: ["hol.org.uk"],
    difficulty: "impossible",
    cancellationUrl: "http://hol.org.uk/profile.php?view=quithol",
    notes: "You can remove information and manually quit HOL, but your account stays forever.",
  },
  {
    name: "Hostelsclub",
    hostnames: ["hostelsclub.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.hostelsclub.com/",
    notes: "You can remove every information from your account or if you signed up using a social network disconnect it.",
  },
  {
    name: "Huddle",
    hostnames: ["huddle.com"],
    difficulty: "hard",
    cancellationUrl: "https://huddle.zendesk.com/hc/en-us/articles/200124703-How-do-I-cancel-my-Huddle-account-",
    notes: null,
  },
  {
    name: "InfiBot",
    hostnames: ["infibot.com"],
    difficulty: "hard",
    cancellationUrl: "https://infibot.com/",
    notes: "Email customer support. Requests are handled within 48 hours.",
  },
  {
    name: "Ingress",
    hostnames: ["ingress.com"],
    difficulty: "hard",
    cancellationUrl: "https://support.google.com/ingress/answer/2870382",
    notes: "You need to fill in the form linked in the support article by clicking \"contact us\". Fill in your email address, agent name, device you play on and submit the form.",
  },
  {
    name: "Instructables",
    hostnames: ["instructables.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.instructables.com/",
    notes: "You have to email them (service@instructables.com) to get your account deleted",
  },
  {
    name: "Internetometer",
    hostnames: ["internetometer.com"],
    difficulty: "impossible",
    cancellationUrl: "http://internetometer.com/",
    notes: "Site provides no user account management interface or account deletion options. Email sent to internets@technoized.com was never replied to.",
  },
  {
    name: "Hacker News",
    hostnames: ["jacquesmattheij.com"],
    difficulty: "impossible",
    cancellationUrl: "http://jacquesmattheij.com/The+Unofficial+HN+FAQ#deleteaccount",
    notes: "Your contributions are there to stay, but you can at least clear out your profile -- even your email address.",
  },
  {
    name: "Kik",
    hostnames: ["kikinteractive.zendesk.com", "kik.com"],
    difficulty: "impossible",
    cancellationUrl: "https://kikinteractive.zendesk.com/entries/23593116-How-do-I-deactivate-my-account-",
    notes: "You can only deactivate your account. There appears to be no way to permanently delete your account or data.",
  },
  {
    name: "Kongregate",
    hostnames: ["kongregate.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.kongregate.com/forums/7/topics/241772?page=1#posts-5207538",
    notes: "You are unable to remove an account, but they can permanently ban your account upon request. They will remove stored information upon request as well, such as e-mail address, developer payment information, and stored payment information.",
  },
  {
    name: "Kraken",
    hostnames: ["kraken.com", "support.kraken.com"],
    difficulty: "hard",
    cancellationUrl: "https://support.kraken.com/hc/en-us/articles/203727206-How-can-I-delete-my-Kraken-account-",
    notes: "To close your account, you need to submit a request to support, which may take up to 24 hours to process.",
  },
  {
    name: "Adobe",
    hostnames: ["learn.adobe.com", "adobe.com"],
    difficulty: "hard",
    cancellationUrl: "https://learn.adobe.com/wiki/display/wel/Delete+your+account",
    notes: "You have to call them in order to delete your account. Alternatively, you can send them an email.",
  },
  {
    name: "Deadspin (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Gawker (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Gizmodo (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "IO9 (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Jalopnik (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Jezebel (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Kinja (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Kotaku (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Lifehacker (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Valleywag (Gawker Media)",
    hostnames: ["legal.kinja.com", "kinja.com"],
    difficulty: "impossible",
    cancellationUrl: "http://legal.kinja.com/kinja-terms-of-use-90161644",
    notes: "You may discontinue your use of the Service at any time without informing us. We may, however, retain and continue to use any Content that you have submitted or uploaded through the Service.",
  },
  {
    name: "Linsensuppe",
    hostnames: ["linsensuppe.de"],
    difficulty: "impossible",
    cancellationUrl: "https://www.linsensuppe.de",
    notes: "One cannot even change the password",
  },
  {
    name: "MisterWong",
    hostnames: ["mister-wong.de"],
    difficulty: "hard",
    cancellationUrl: "http://www.mister-wong.de",
    notes: "You need to send an email to support and it may take up to 48 hours to process your request.",
  },
  {
    name: "Mobify",
    hostnames: ["mobify.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.mobify.com/contact/",
    notes: "You have to send a message in order to remove your account.",
  },
  {
    name: "Moonpig",
    hostnames: ["moonpig.com", "moonpig.co.uk"],
    difficulty: "hard",
    cancellationUrl: "https://photobox-mp.custhelp.com/",
    notes: "Contact customer services and they'll respond in 24-48 hours. Not to mention the ways they try to hide you removing your card details. If you want to remove your card details, do the following: The easiest way to do this would be to go to the My Account page then click on the \u2018Add Moonpig Prepay Credit\u2019 link, click on the Buy link and your saved card details will be shown onscreen. Click on the \u2018Remove Card\u2019 option.",
  },
  {
    name: "Multiplay.co.uk",
    hostnames: ["multiplay.com"],
    difficulty: "hard",
    cancellationUrl: "https://multiplay.com/contactus/",
    notes: "You have to contact Multiplay by their contact us page.",
  },
  {
    name: "CloudApp",
    hostnames: ["my.cl.ly", "cl.ly"],
    difficulty: "hard",
    cancellationUrl: "http://my.cl.ly/account/delete",
    notes: "The site claims that you must call their support line (888-988-5036, ext 1), but they deactivated my account over email.",
  },
  {
    name: "New York Times",
    hostnames: ["myaccount.nytimes.com", "nytimes.com"],
    difficulty: "hard",
    cancellationUrl: "https://myaccount.nytimes.com/membercenter/help.html",
    notes: "Use the form to write to customer services and ask them to close your account.",
  },
  {
    name: "Nearpod",
    hostnames: ["nearpod.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.nearpod.com/contact/",
    notes: "Requires to fill out contact form. Will still get Promotional emails until you also unsubscribe from them",
  },
  {
    name: "Neopets",
    hostnames: ["neopets.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.neopets.com/help_search.phtml?help_id=4",
    notes: "Send an email to the unsubscribe@neopets.com stating you wish to delete your account.",
  },
  {
    name: "Ubuntu One",
    hostnames: ["one.ubuntu.com", "ubuntu.com"],
    difficulty: "hard",
    cancellationUrl: "https://one.ubuntu.com/help/faq/how-can-i-delete-my-account/",
    notes: "Yes and no, it depends on which type(s) of accounts, and you will need to delete the accounts in the correct order. All accounts are tied to Ubuntu One's Single Sign-On (login.ubuntu.com), so that is the account you should close last. Everything else, such as Launchpad.net, cloud file storage, AskUbuntu, and other accounts should be closed first if possible. This is especially important if you have any paid services attached, to make sure you won't be billed for anything after closing the accounts. The last step is to delete your Single Sign-On (SSO) account. SSO accounts must be deleted manually by the Ubuntu One staff.",
  },
  {
    name: "OnlineTVRecorder.com",
    hostnames: ["onlinetvrecorder.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.onlinetvrecorder.com/v2/index.php?go=account&do=cancel",
    notes: "You can deactivate your account with the link. But the data isn't deleted. Even if you contact the support they don't delete your data.",
  },
  {
    name: "OnLive",
    hostnames: ["onlive.com"],
    difficulty: "impossible",
    cancellationUrl: "https://support.onlive.com/requests/new",
    notes: "It's possible to close your account if you request it, but it's not possible to delete it.",
  },
  {
    name: "OpenDNS",
    hostnames: ["opendns.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.opendns.com/support/contact/",
    notes: "You must open a ticket to completely get your account deleted.",
  },
  {
    name: "DHL (Paket.de)",
    hostnames: ["paket.de"],
    difficulty: "impossible",
    cancellationUrl: "https://www.paket.de/pkp/appmanager/pkp/desktop?_nfpb=true&_nfxr=false&_pageLabel=pkp_portal_page_footer_cah_faqs",
    notes: "There's no information about account-deletion in their FAQ. The hotline also says that account-deletion isn't possible.",
  },
  {
    name: "Parkmobile",
    hostnames: ["parkmobile.us", "parkmobile.com", "parkmobile.zendesk.com"],
    difficulty: "hard",
    cancellationUrl: "https://parkmobile.zendesk.com/hc/en-us/articles/203299300-How-do-I-cancel-my-account-",
    notes: "To cancel your account, send an e-mail message request to the Parkmobile Help Desk at helpdesk@parkmobileglobal.com and include your name, mobile number, license plate number, and/or the last 4 digits of the card we have on file for you. After the Help Desk cancels your account, you will receive a confirmation e-mail message.",
  },
  {
    name: "Pastebin",
    hostnames: ["pastebin.com"],
    difficulty: "impossible",
    cancellationUrl: "http://pastebin.com/profile",
    notes: "You can remove your pastes, but there's no link to delete your account.",
  },
  {
    name: "PayPal",
    hostnames: ["paypal.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.paypal.com/us/cgi-bin/webscr?cmd=_close-account",
    notes: "Log in. Click 'Profile' near the top of the page. Click 'My settings'. Click 'Close Account' in the 'Account type' section and follow the steps listed.",
  },
  {
    name: "PCPartPicker",
    hostnames: ["pcpartpicker.com"],
    difficulty: "hard",
    cancellationUrl: "http://pcpartpicker.com/contact/",
    notes: "I had to contact via email, but they then immediately deleted my account",
  },
  {
    name: "Peak",
    hostnames: ["peak.net"],
    difficulty: "hard",
    cancellationUrl: "http://www.peak.net/",
    notes: "You must send an e-mail to support@peak.net requesting deletion. You will then receive a response from support asking for feedback and to confirm the deletion. The next e-mail you receive from support will notify you that your account has been deleted.",
  },
  {
    name: "We the People",
    hostnames: ["petitions.whitehouse.gov", "whitehouse.gov"],
    difficulty: "impossible",
    cancellationUrl: "https://petitions.whitehouse.gov/",
    notes: "Site provides no user account management interface or account deletion options.",
  },
  {
    name: "PhishTank",
    hostnames: ["phishtank.com"],
    difficulty: "impossible",
    cancellationUrl: "https://www.phishtank.com/",
    notes: null,
  },
  {
    name: "PHP Classes",
    hostnames: ["phpclasses.org"],
    difficulty: "impossible",
    cancellationUrl: "http://www.phpclasses.org/faq/#delete-account",
    notes: "They refuse to delete accounts from the site.",
  },
  {
    name: "Picasa",
    hostnames: ["picasaweb.google.com", "picasa.google.com"],
    difficulty: "impossible",
    cancellationUrl: "http://picasaweb.google.com/",
    notes: "You can't delete your Google Account for Picasa Web Albums without deleting your entire Google Account.",
  },
  {
    name: "Pinboard",
    hostnames: ["pinboard.in"],
    difficulty: "hard",
    cancellationUrl: "https://pinboard.in/faq/#close_account",
    notes: "Send us an e-mail from the address that you have registered - we take care of it.",
  },
  {
    name: "Pinterest",
    hostnames: ["pinterest.com"],
    difficulty: "impossible",
    cancellationUrl: "https://pinterest.com/settings/",
    notes: "Accounts can be deactivated, which means that your pins and profile are hidden but not deleted.",
  },
  {
    name: "Points.com",
    hostnames: ["questions.points.com", "points.com"],
    difficulty: "hard",
    cancellationUrl: "http://questions.points.com/entries/20026692-How-do-I-cancel-my-account-",
    notes: "Must contact support through Contanct form or online chat.",
  },
  {
    name: "Quora",
    hostnames: ["quora.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.quora.com/Quora-product/How-do-I-delete-my-Quora-account",
    notes: "First deactivate your account. Log in, go to 'Settings', 'Privacy', and then 'Deactivate Account'. You can then e-mail privacy@quora.com if you want to completely delete your account.",
  },
  {
    name: "RateYourMusic",
    hostnames: ["rateyourmusic.com"],
    difficulty: "impossible",
    cancellationUrl: "http://rateyourmusic.com/account/delete",
    notes: "After deleteing the account, it will be deactivated for 30 days before being deleted permanently. Messages, forum posts, and contributions stay on the site even after your account is deleted.",
  },
  {
    name: "Readability",
    hostnames: ["readability.com"],
    difficulty: "impossible",
    cancellationUrl: "https://www.readability.com/account/delete",
    notes: "You can't delete your account, but you can deactivate it.",
  },
  {
    name: "Redditgifts",
    hostnames: ["redditgifts.com"],
    difficulty: "hard",
    cancellationUrl: "http://redditgifts.com/privacy/",
    notes: "If you decide you would like to delete your account you must email us at support@redditgifts.com. You must email us from the email address associated with your account and provide your reddit username.",
  },
  {
    name: "Rideindego",
    hostnames: ["rideindego.com"],
    difficulty: "impossible",
    cancellationUrl: "https://www.rideindego.com/faq/how-do-i-cancel-my-membership/",
    notes: "You can only cancel the auto-renewal feature. I called them and asked to cancel my account and be removed from their mailing list and they told me my account was already not renewing and there was nothing else they could do.",
  },
  {
    name: "Roblox",
    hostnames: ["roblox.com"],
    difficulty: "impossible",
    cancellationUrl: "https://en.help.roblox.com/hc/en-us/articles/203313050-How-Do-I-Delete-My-Account-",
    notes: "Not possible. 'We currently do not have a feature for players to delete their accounts. If you no longer wish to play on your account, it will remain inactive until you're ready to play again.'",
  },
  {
    name: "Booklooker",
    hostnames: ["secure.booklooker.de", "booklooker.de"],
    difficulty: "hard",
    cancellationUrl: "https://secure.booklooker.de/pages/contact.php",
    notes: "You need to request deletion of your data via the contact form after logging in.",
  },
  {
    name: "Moped",
    hostnames: ["secure.moped.com", "moped.com"],
    difficulty: "hard",
    cancellationUrl: "https://secure.moped.com/account/support",
    notes: "You need send email to support and it may take up to 24 hours to process your request.",
  },
  {
    name: "Runescape",
    hostnames: ["services.runescape.com", "runescape.com"],
    difficulty: "hard",
    cancellationUrl: "http://services.runescape.com/m=rswiki/en/Account_Help",
    notes: "Under 5. Account Settings > A. Account Management > V. Account Deletion. You must mail or fax an affidavit to the Runescape office along with a copy of your legal identification",
  },
  {
    name: "showRSS",
    hostnames: ["showrss.info"],
    difficulty: "impossible",
    cancellationUrl: "http://showrss.info/",
    notes: null,
  },
  {
    name: "Shutterfly",
    hostnames: ["shutterfly.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.shutterfly.com/about/contact_details.jsp",
    notes: "Contact customers services by email or live chat and request deletion.",
  },
  {
    name: "Shutterstock",
    hostnames: ["shutterstock.com"],
    difficulty: "hard",
    cancellationUrl: "http://submit.shutterstock.com/privacy.mhtml",
    notes: "If you wish to delete your account or request that we no longer use your information to provide you services contact us at Support@Shutterstock.com.",
  },
  {
    name: "SigFig",
    hostnames: ["sigfig.com"],
    difficulty: "hard",
    cancellationUrl: "https://support.sigfig.com/hc/en-us/articles/202586434-How-do-I-completely-delete-my-account-",
    notes: "Contact customer service by email and request deletion.",
  },
  {
    name: "Simple Machines",
    hostnames: ["simplemachines.org"],
    difficulty: "hard",
    cancellationUrl: "http://www.simplemachines.org/community/index.php?action=profile;area=deleteaccount",
    notes: "Enter your password to have your account marked for deletion by an administrator or moderator. You can do this for any other Simple Machines forums if the forum administrator allows.",
  },
  {
    name: "Slashdot",
    hostnames: ["slashdot.org"],
    difficulty: "impossible",
    cancellationUrl: "http://slashdot.org/faq/#accounts3",
    notes: null,
  },
  {
    name: "SlimTimer",
    hostnames: ["slimtimer.com"],
    difficulty: "hard",
    cancellationUrl: "http://slimtimer.com/",
    notes: "Email request required.",
  },
  {
    name: "SmartRecruiters",
    hostnames: ["smartrecruiters.com"],
    difficulty: "hard",
    cancellationUrl: "http://help.smartrecruiters.com/customer/portal/articles/1498239-how-can-i-close-my-account-",
    notes: null,
  },
  {
    name: "Morningstar",
    hostnames: ["socialize.morningstar.com", "morningstar.com"],
    difficulty: "hard",
    cancellationUrl: "http://socialize.morningstar.com/feedback/feedbackform.asp",
    notes: "Fill out the feedback form, asking them to delete your account. Be sure to specify that you\u2019re not just unsubscribing from e-mail but that you want your account deleted entirely.",
  },
  {
    name: "Soluto",
    hostnames: ["soluto.com", "support.soluto.com"],
    difficulty: "hard",
    cancellationUrl: "https://support.soluto.com/requests/new",
    notes: "You need to create a support ticket and set the subject to Delete Account.",
  },
  {
    name: "Sonico",
    hostnames: ["sonico.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.sonico.com/tyc.php",
    notes: "Send a request to legal@sonico.com and request deletion.",
  },
  {
    name: "soup.io",
    hostnames: ["soup.io"],
    difficulty: "hard",
    cancellationUrl: "http://www.soup.io/about",
    notes: "Put 'delete me' in the description box on your profile and mail team@soup.io with your soup URL and request a deletion",
  },
  {
    name: "Speaker Deck",
    hostnames: ["speakerdeck.com"],
    difficulty: "impossible",
    cancellationUrl: "https://speakerdeck.com/tos",
    notes: "If you wish to terminate your Speaker Deck account, you may simply discontinue using Speaker Deck.",
  },
  {
    name: "Stack Overflow / Stack Exchange Accounts",
    hostnames: ["stackoverflow.com"],
    difficulty: "hard",
    cancellationUrl: "http://stackoverflow.com/help/deleting-account",
    notes: "If you haven\u2019t posted on the site, it\u2019s just one click. If you have voted or posted, please contact the Stack Exchange Team: Visit the contact form and select \u2018I need to delete my user profile\u2019. After you contact us, the team will reach out with further instructions.",
  },
  {
    name: "StepMap",
    hostnames: ["stepmap.de"],
    difficulty: "hard",
    cancellationUrl: "http://www.stepmap.de/profil.php",
    notes: "To delete your StepMap account, let us know by sending an e-mail with info@stepmap.de and enter your username. The sender address must be your e-mail address that you have subscribed to at StepMap.",
  },
  {
    name: "Intel Education Study (was Kno)",
    hostnames: ["study.intel.com"],
    difficulty: "hard",
    cancellationUrl: "https://www.study.intel.com/support",
    notes: "You can close your account if you contact customer service either by phone or live chat",
  },
  {
    name: "Stypi",
    hostnames: ["stypi.com"],
    difficulty: "impossible",
    cancellationUrl: "https://code.stypi.com/faq",
    notes: "If you have an account, you can delete any document by right clicking the file and selecting 'Delete'. If you do not have an account please email support@stypi.com.",
  },
  {
    name: "CrashPlan",
    hostnames: ["support.crashplan.com", "crashplan.com"],
    difficulty: "hard",
    cancellationUrl: "http://support.crashplan.com/",
    notes: "Start a live chat session and a representative will delete your account.",
  },
  {
    name: "Dropmark",
    hostnames: ["support.dropmark.com", "dropmark.com"],
    difficulty: "hard",
    cancellationUrl: "http://support.dropmark.com/customer/portal/questions/564826-deleting-my-account",
    notes: null,
  },
  {
    name: "GoDaddy",
    hostnames: ["support.godaddy.com", "godaddy.com"],
    difficulty: "impossible",
    cancellationUrl: "http://support.godaddy.com/groups/go-daddy-customers/forum/topic/how-do-i-delete-my-account-with-godaddy/",
    notes: "GoDaddy Accounts are apparently retained \u201cto comply with [their] legal obligations\u201d though you are able to clear out most of your information by editing your profile.",
  },
  {
    name: "League of Legends",
    hostnames: ["support.leagueoflegends.com", "leagueoflegends.com"],
    difficulty: "impossible",
    cancellationUrl: "https://support.leagueoflegends.com/entries/461131-Disabling-Your-Account",
    notes: "Accounts may be disabled, but some data will be retained. E-mail support@riotgames.com with the subject \"Account Deactivation\" and include your username, summoner name, server and email used when registering the account in your ticket",
  },
  {
    name: "Netflix",
    hostnames: ["support.netflix.com", "netflix.com"],
    difficulty: "impossible",
    cancellationUrl: "https://support.netflix.com/en/node/407",
    notes: "Contact customer services. Even then they may not delete your account under the premise that you might want to rejoin and keep your history and recommendations.",
  },
  {
    name: "Skype",
    hostnames: ["support.skype.com", "skype.com"],
    difficulty: "hard",
    cancellationUrl: "https://support.skype.com/en/faq/FA142/can-i-delete-my-skype-account",
    notes: "Contact customer services on chat. You\u2019ll need to know whether you bought services from Skype, you\u2019ll need to verify your signup email address.",
  },
  {
    name: "Steam",
    hostnames: ["support.steampowered.com", "steampowered.com"],
    difficulty: "impossible",
    cancellationUrl: "https://support.steampowered.com/newticket.php",
    notes: "If you contact Steam support, they will most likely tell you just to not use the account. If your account has no games on it, it will be disabled after a while.",
  },
  {
    name: "TED",
    hostnames: ["support.ted.com", "ted.com"],
    difficulty: "hard",
    cancellationUrl: "http://support.ted.com/customer/portal/articles/143809-i-d-like-to-delete-my-account",
    notes: "TED has to be contacted via e-mail for account deletion requests",
  },
  {
    name: "Transifex",
    hostnames: ["support.transifex.com", "transifex.com"],
    difficulty: "impossible",
    cancellationUrl: "http://support.transifex.com/customer/portal/articles/1052765-how-can-i-delete-my-account-",
    notes: "You can't delete your account, but you can contact them via email to deactivate it.",
  },
  {
    name: "PlayStation Network",
    hostnames: ["support.us.playstation.com", "playstation.com"],
    difficulty: "impossible",
    cancellationUrl: "https://support.us.playstation.com/app/contact_options",
    notes: "It is not possible to delete your PlayStation Network account.  The best you can do is delete any personal information that you have stored on their website.",
  },
  {
    name: "Torrent 411",
    hostnames: ["t411.me"],
    difficulty: "hard",
    cancellationUrl: "https://www.t411.me/contactstaff/",
    notes: "you have to ask the staff to delete your account",
  },
  {
    name: "Technorati",
    hostnames: ["technorati.com"],
    difficulty: "impossible",
    cancellationUrl: "http://technorati.com",
    notes: "It's not possible to remove your account, but you can remove your blogs.",
  },
  {
    name: "Ticketmaster",
    hostnames: ["ticketmaster.com"],
    difficulty: "hard",
    cancellationUrl: "http://help.ticketmaster.com/contact-us/",
    notes: "You must submit a request to close your account via the form.",
  },
  {
    name: "TinyDeal",
    hostnames: ["tinydeal.com"],
    difficulty: "impossible",
    cancellationUrl: "http://help.tinydeal.com/contact-us",
    notes: "You will most likely be told that it's impossible to delete your account when contacting customer service.",
  },
  {
    name: "Topcoder",
    hostnames: ["topcoder.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.topcoder.com/help/p=636/",
    notes: "You can't delete your account, but you can contact them via email to deactivate it.",
  },
  {
    name: "Usersnap",
    hostnames: ["usersnap.com"],
    difficulty: "hard",
    cancellationUrl: "https://usersnap.com/contact",
    notes: "Send an email with the subject \u2018Delete my account\u2019",
  },
  {
    name: "Verduca",
    hostnames: ["veduca.com.br"],
    difficulty: "impossible",
    cancellationUrl: "http://www.veduca.com.br",
    notes: null,
  },
  {
    name: "Vine",
    hostnames: ["vine.co"],
    difficulty: "hard",
    cancellationUrl: "https://support.twitter.com/forms/vine",
    notes: "The only way to delete your Vine account without deleting your Twitter account is to contact Twitter through their contact form.",
  },
  {
    name: "Western Union",
    hostnames: ["westernunion.ch", "westernunion.com"],
    difficulty: "hard",
    cancellationUrl: "https://thewesternunion.custhelp.com/app/answers/detail/a_id/116/~/how-do-i-cancel-my-western-union-account%2Fprofile%3F",
    notes: null,
  },
  {
    name: "WolframAlpha.com",
    hostnames: ["wolframalpha.com"],
    difficulty: "hard",
    cancellationUrl: "http://www.wolframalpha.com/fbfaqs.html",
    notes: "For the immediate future, send a message to WolframAlpha, and your Wolfram ID will be deleted manually.",
  },
  {
    name: "Xfire",
    hostnames: ["xfire.com"],
    difficulty: "impossible",
    cancellationUrl: "http://www.xfire.com/faq#1",
    notes: "There is no way to delete your account, you can only make some information private and/or delete it.",
  },
  {
    name: "YouTube",
    hostnames: ["youtube.com"],
    difficulty: "impossible",
    cancellationUrl: "https://support.google.com/youtube/answer/55759",
    notes: "You can\u2019t delete your YouTube account without deleting your entire Google or Google+ account. But you can delete your YouTube channel.",
  },
  {
    name: "Zynga",
    hostnames: ["zynga.com"],
    difficulty: "hard",
    cancellationUrl: "https://zynga.com/privacy/faqs",
    notes: "Place Delete My Account in the subject line and include your first name, last name, e-mail address and user ID number for the SNS from which you access our games (if applicable) in the body of the e-mail.",
  },
];
